<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMedrMwL\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMedrMwL/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerMedrMwL.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerMedrMwL\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerMedrMwL\appAppKernelProdContainer([
    'container.build_hash' => 'MedrMwL',
    'container.build_id' => 'dc9645c5',
    'container.build_time' => 1709566004,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMedrMwL');
