<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHRFk80B\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHRFk80B/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerHRFk80B.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerHRFk80B\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerHRFk80B\appAppKernelProdContainer([
    'container.build_hash' => 'HRFk80B',
    'container.build_id' => '09005623',
    'container.build_time' => 1709929007,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHRFk80B');
